[package]
name = "signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
ecdsa = "0.16.9"
hex = "0.4.3"
k256 = "0.13.2"
sha2 = "0.10.8"
sha256 = "1.4.0"
